### ISSUE TITLE
配置第三方插件库 

### ISSUE THREAD

**Issue by Xiaoshizi1024** [Xiaoshizi1024/wukong-robot#6]
## 目的 

 配置wukong的第三方资源，来给自己的机器人增加更加多的功能 

## 资源

- 官方资料：[用户贡献技能 - wukong-robot](https://wukong.hahack.com/#/contrib)  
- 插件仓库 [wzpan/wukong-contrib: 来自用户贡献的wukong-robot插件集](https://github.com/wzpan/wukong-contrib) 

## 会存在的问题 

有些插件即便配置成果了，但是还是会因为没有更新而无法使用 

## 行动 
- [X] 新闻
- [ ] 公交路线查询
- [X] BaiduFM插件配置
- [ ] 翻译 
- [ ] Hass 智能设备
- [ ] 点灯
- [X] 微博查询技能

**Comment by Xiaoshizi1024** [comment]
## 新闻 

- [X] 注册API
- [X] 连接API
- [X] 检测效果

**行动** 

1. 注册API 

个人信息
- QQ邮箱
- 主手机号
- 密码 初始化
- 身份证验证

API： c990452046c3759010f1683c2ab1877b


唤醒词： 
- 新闻头条
- 体育新闻
- 头条（默认）、社会、国内、国际、娱乐、体育、军事、财经、时尚 ....

**Comment by Xiaoshizi1024** [comment]
## 百度音乐插件 OK

**唤醒词**
- 播放百度音乐

音乐控制命令
- 下一首、切歌、下一首歌、下首歌
- 上一首、上一首歌、上首歌
- 停止播放、结束播放、退出播放
- 换歌   播放列表
- 什么歌  

配置文档：
```
baidufm:
    channel: 14  # 默认频道，如果没有配置，默认选择90后频道，更多频道见下表
    location: '郑州'
```

---  

190521 补充 
昨天测试，通过镜像重装之后，百度音乐 插件并不能完全调取... 
可能需要进行的操作
- 升级wukong版本 或 程序第三方库版本~  
- 风险
    * 升级wukong会导致 升级失败；在显示上会不显示文字等问题...
    * 升级 第三方插件库，可能会 导致之前测试的功能不能用... 

**觉察**  
- 在学习配置第三方插件库的时候，就没有考虑到当时所处的环境背景，比如说 wukong的版本，第三方库的版本问题...

**Comment by Xiaoshizi1024** [comment]
## 线路查询  Direction   失败

- [X] 注册API
- [x] 配置API
- [x] 检测效果  不能用...


```
# 出行线路规划插件
# 百度LBS Web服务API
# http://lbsyun.baidu.com/index.php?title=webapi
direction:
    app_key: 你申请到的app key
    origin: 出发起始地坐标，可在此http://api.map.baidu.com/lbsapi/getpoint/获取，如:"39.91405,116.404269",纬度在前，经度在后
```

1. 注册API 

账号： 百度账号
ref: [百度地图开放平台 | 百度地图API SDK | 地图开发](http://lbsyun.baidu.com/apiconsole/key) 
AK : oT4iSAN0LNPwHxieCiD3hri8hhmbLd4t

2. 配置

```
# 出行线路规划插件
# 百度LBS Web服务API
# http://lbsyun.baidu.com/index.php?title=webapi
direction:
    app_key: "oT4iSAN0LNPwHxieCiD3hri8hhmbLd4t"
    origin: "113.515318,34.714583" #出发起始地坐标，可在此http://api.map.baidu.com/lbsapi/getpoint/获取，如:"39.91405,116.404269",纬度在前，经度在后

```

3. 检测效果 

参考：
```
用户：线路
悟空：去哪里
用户：世纪大道
悟空：世纪大道-地铁站参考路线:步行169米.锦绣路站(4口)乘地铁7号线(花木路方向)经过2站到龙阳路站.站内换乘 步行170米.龙阳路站乘地铁2号线(徐泾东方向)经过3站到世纪大道站.
``` 

用户：线路
叮咚：去哪里
用户：二七广场 /郑州火车站 
悟空：无响应...
